import React from 'react';
import {Link} from 'react-router-dom';

const CaseStudy = () => {
  return (
    <div>
      <p>Case study</p>
      <p>In order to establish accessibility standards throughout government-run technology applications, allowing for anyone with or without a disability to interact with fundamental government websites, kiosks, and mobile applications, Section 508 of the Rehabilitation Act was established in 1998. This Section outlines all of the necessary components of web infrastructure to keep its promise to ensure applications are accessible to all. Section 508.C is fundamental to this project, as it outlines the necessity for applications to not use color just to portray important information, and it ensures color contrast levels meet the WCAG AAA standards. This relates directly to this web application, as its main focus is to outline and teach the necessity of proper color contrast in order to ensure individuals with a color vision deficiency can properly identify prominent information in student’s web applications moving forward.
	Existing validators, such as WebAIM’s Color Contrast Calculator help to ensure this standard is met. Color contrast calculators work by a user inputting a background color as well as the color of the text they are hoping to use for their application. An algorithm is used to determine how, when justified on top of one another, what ratio of difference there is between the two colors. This ratio is then used to determine if the color contrast is high enough for an individual with a color vision deficiency to be able to discern between the two colors. If the ratio is too low, an individual with a color vision deficiency could potentially either miss altogether or have a very difficult time seeing text that could be vital to their use of the application. An example of this would be a user agreement hidden behind too low of contrasting colors, like in the AirBnB example above. An individual with a color vision deficiency could miss the agreement and then could violate the company’s guidelines. In court, the individual with the deficiency could sue the company for damages, as they were unable to see the rules and regulations in the first place. With proper color contrast, this issue can be avoided, and the individual would be able to see the agreement, ensuring that the individual could not sue for damages. The proper WCAG AAA standard places proper color contrast at a rating of seven to one for font sizing twelve pixels to eighteen pixels, and four point five to one for font sizing eighteen pixels or above.</p>
      <p>The importance of color contrast rings true throughout the internet, as multiple publications each year host lists featuring the worst website designs. Most of these designs bost horrendous color contrasts that even a person without a color vision deficiency has issues seeing the webpage. Each and every year, however, it seems that Yale’s School of Art has one of the largest issues with color contrast. Year after year individuals online complain about clashing background and foreground elements. When a background picture is updated on the site, there is little to no thought that goes into changing the foreground elements to ensure the colors don’t contrast one another too heavily. So far, there has not been a lawsuit over the issue, but it continues to be one of the top listed items on forums for the worst web design with the main complaint being color contrast.
	As software developers, we have a professional responsibility to uphold the Association for Computing Machinery (ACM) code of ethics, the Convention on the Rights of Persons with Disabilities (CRPD), and our own personal morals. We as individuals must ensure that we contribute to society and to human well-being, acknowledging that all people are stakeholders in computing (ACM 1.1) and that we are fair and take action not to discriminate (ACM 1.4). On top of this, we must take into account the protection and promotion of the human rights of persons with disabilities in all policies and programmes, including our web development (CRPD Article 4.C). In order to ensure we are compliant with all of these professional responsibilities, as well as ensure we as individuals are upholding our own morals, color contrast must be considered in everything we create for the web, as without it, we are not treating individuals with a color vision deficiency as a stakeholder in computing, we are discriminating against their use of our applications, and we are not protecting the rights of these individuals to be able to access the internet the same as everyone else. Color contrast and Section 508.C is vital to the continued success of web applications on the internet.</p>
      <Link to='/suppMaterials'>Go Back to Supplementary Materials</Link>
    </div>
  );
}

export default CaseStudy;
