export const SELECT_OPTION = "SELECT_OPTION";
export const RESET_OPTION = "RESET_OPTION";

export const UPDATE_DEFAULT_COLORS = "UPDATE_DEFAULT_COLORS";
export const UPDATE_GAME_COLORS = "UPDATE_GAME_COLORS";
export const ACTIVATE_POPUP = "ACTIVATE_POPUP";
export const RESET_COLORS = "RESET_COLORS";

export const START_GAME = "START_GAME";
export const END_GAME = "END_GAME";

export const LOGIN = "LOGIN";
